### ISSUE TITLE
The function 'row_number' must have an OVER clause with ORDER BY

### ISSUE THREAD

**Issue by aatauil** [brechtvdv/adlib2eventstream#16]
Method: docker , docker-compose
Database: mssql (mcr.microsoft.com/mssql/server:2019-latest)

**Reproduce**
Set up the app using docker and use mssql as database. Open the eventstream page and press on one of the "toegangsURL". 

<details>
 <summary>Logs</summary>

```

eventstream_1    | Executing (default): SELECT max([generatedAtTime]) AS [max] FROM [Members] AS [Member] WHERE ([Member].[institution] = N'adlib' AND [Member].[database] = N'personen' AND ([Member].[generatedAtTime] <= N'2021-04-30 08:47:17.033 +00:00' AND [Member].[generatedAtTime] IN 
eventstream_1    |             (select "generatedAtTime"
eventstream_1    |             from (select "generatedAtTime", row_number() over () - 1 rownr
eventstream_1    |                   from "Members"
eventstream_1    |                   where institution='adlib'
eventstream_1    |                   AND database='personen'
eventstream_1    |                   group by "generatedAtTime") AS distinctGeneratedAtTimes
eventstream_1    |             where rownr % 5 = 0
eventstream_1    |             )));
eventstream_1    | { SequelizeDatabaseError: The function 'row_number' must have an OVER clause with ORDER BY.
eventstream_1    |     at Query.formatError (/usr/src/app/node_modules/sequelize/lib/dialects/mssql/query.js:314:12)
eventstream_1    |     at Query._run (/usr/src/app/node_modules/sequelize/lib/dialects/mssql/query.js:93:18)
eventstream_1    |     at process._tickCallback (internal/process/next_tick.js:68:7)
eventstream_1    |   name: 'SequelizeDatabaseError',
eventstream_1    |   parent:
eventstream_1    |    { RequestError: The function 'row_number' must have an OVER clause with ORDER BY.
eventstream_1    |        at Parser.tokenStreamParser.on.token (/usr/src/app/node_modules/tedious/lib/connection.js:1160:27)
eventstream_1    |        at Parser.emit (events.js:198:13)
eventstream_1    |        at Readable.Parser.parser.on.token (/usr/src/app/node_modules/tedious/lib/token/token-stream-parser.js:27:14)
eventstream_1    |        at Readable.emit (events.js:198:13)
eventstream_1    |        at addChunk (/usr/src/app/node_modules/readable-stream/lib/_stream_readable.js:298:12)
eventstream_1    |        at readableAddChunk (/usr/src/app/node_modules/readable-stream/lib/_stream_readable.js:280:11)
eventstream_1    |        at Readable.push (/usr/src/app/node_modules/readable-stream/lib/_stream_readable.js:241:10)
eventstream_1    |        at /usr/src/app/node_modules/readable-stream/lib/internal/streams/from.js:49:29
eventstream_1    |        at Generator.next (<anonymous>)
eventstream_1    |        at asyncGeneratorStep (/usr/src/app/node_modules/readable-stream/lib/internal/streams/from.js:3:103)
eventstream_1    |      message:
eventstream_1    |       'The function \'row_number\' must have an OVER clause with ORDER BY.',
eventstream_1    |      code: 'EREQUEST',
eventstream_1    |      number: 4112,
eventstream_1    |      state: 1,
eventstream_1    |      class: 15,
eventstream_1    |      serverName: '37a3a7974eab',
eventstream_1    |      procName: '',
eventstream_1    |      lineNumber: 3,
eventstream_1    |      sql:
eventstream_1    |       'SELECT max([generatedAtTime]) AS [max] FROM [Members] AS [Member] WHERE ([Member].[institution] = N\'adlib\' AND [Member].[database] = N\'personen\' AND ([Member].[generatedAtTime] <= N\'2021-04-30 08:47:17.033 +00:00\' AND [Member].[generatedAtTime] IN \n            (select "generatedAtTime"\n            from (select "generatedAtTime", row_number() over () - 1 rownr\n                  from "Members"\n                  where institution=\'adlib\'\n                  AND database=\'personen\'\n                  group by "generatedAtTime") AS distinctGeneratedAtTimes\n            where rownr % 5 = 0\n            )));',
eventstream_1    |      parameters: undefined },
eventstream_1    |   original:
eventstream_1    |    { RequestError: The function 'row_number' must have an OVER clause with ORDER BY.
eventstream_1    |        at Parser.tokenStreamParser.on.token (/usr/src/app/node_modules/tedious/lib/connection.js:1160:27)
eventstream_1    |        at Parser.emit (events.js:198:13)
eventstream_1    |        at Readable.Parser.parser.on.token (/usr/src/app/node_modules/tedious/lib/token/token-stream-parser.js:27:14)
eventstream_1    |        at Readable.emit (events.js:198:13)
eventstream_1    |        at addChunk (/usr/src/app/node_modules/readable-stream/lib/_stream_readable.js:298:12)
eventstream_1    |        at readableAddChunk (/usr/src/app/node_modules/readable-stream/lib/_stream_readable.js:280:11)
eventstream_1    |        at Readable.push (/usr/src/app/node_modules/readable-stream/lib/_stream_readable.js:241:10)
eventstream_1    |        at /usr/src/app/node_modules/readable-stream/lib/internal/streams/from.js:49:29
eventstream_1    |        at Generator.next (<anonymous>)
eventstream_1    |        at asyncGeneratorStep (/usr/src/app/node_modules/readable-stream/lib/internal/streams/from.js:3:103)
eventstream_1    |      message:
eventstream_1    |       'The function \'row_number\' must have an OVER clause with ORDER BY.',
eventstream_1    |      code: 'EREQUEST',
eventstream_1    |      number: 4112,
eventstream_1    |      state: 1,
eventstream_1    |      class: 15,
eventstream_1    |      serverName: '37a3a7974eab',
eventstream_1    |      procName: '',
eventstream_1    |      lineNumber: 3,
eventstream_1    |      sql:
eventstream_1    |       'SELECT max([generatedAtTime]) AS [max] FROM [Members] AS [Member] WHERE ([Member].[institution] = N\'adlib\' AND [Member].[database] = N\'personen\' AND ([Member].[generatedAtTime] <= N\'2021-04-30 08:47:17.033 +00:00\' AND [Member].[generatedAtTime] IN \n            (select "generatedAtTime"\n            from (select "generatedAtTime", row_number() over () - 1 rownr\n                  from "Members"\n                  where institution=\'adlib\'\n                  AND database=\'personen\'\n                  group by "generatedAtTime") AS distinctGeneratedAtTimes\n            where rownr % 5 = 0\n            )));',
eventstream_1    |      parameters: undefined },
eventstream_1    |   sql:
eventstream_1    |    'SELECT max([generatedAtTime]) AS [max] FROM [Members] AS [Member] WHERE ([Member].[institution] = N\'adlib\' AND [Member].[database] = N\'personen\' AND ([Member].[generatedAtTime] <= N\'2021-04-30 08:47:17.033 +00:00\' AND [Member].[generatedAtTime] IN \n            (select "generatedAtTime"\n            from (select "generatedAtTime", row_number() over () - 1 rownr\n                  from "Members"\n                  where institution=\'adlib\'\n                  AND database=\'personen\'\n                  group by "generatedAtTime") AS distinctGeneratedAtTimes\n            where rownr % 5 = 0\n            )));',
eventstream_1    |   parameters: undefined }

```
</details>

**More details**
I did not get this issue when using postgres as database. The issue seems to originate from this line https://github.com/brechtvdv/adlib2eventstream/blob/master/controllers/eventstreamController.js#L33

**Possible solution**
convert the query to the sequelize equivalent

**Comment by brechtvdv** [comment]
Fixed here: 
https://github.com/StadGent/node_service_eventstream-api/commit/2d861e890de5329b4d75d67c67245f2188d76b7d
https://github.com/StadGent/node_service_adlib-backend/commit/a45c1580417de4ac1fef1db3f2dfa210283f3aea
